default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]
ci:
  autofix_prs: false
  autoupdate_schedule: monthly
  autoupdate_commit_msg: "chore(deps): Bump pre-commit hooks"
repos:
  - repo: https://github.com/ComPWA/mirrors-taplo
    rev: v0.9.3
    hooks:
      - id: taplo-format
        name: Format TOML files
      - id: taplo-lint
        name: Lint TOML files
        args: ['--no-schema']
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        name: Lint YAML files
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt
        name: Format shell scripts
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        name: Check shell scripts
  - repo: https://github.com/editorconfig-checker/editorconfig-checker
    rev: v3.4.1
    hooks:
      - id: editorconfig-checker
        name: Check EditorConfig rules
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        name: Detect hardcoded secrets
  - repo: https://github.com/adhtruong/mirrors-typos
    rev: v1.38.1
    hooks:
      - id: typos
        name: Detect spelling typos
        args: ['--force-exclude']
        exclude: '.age'
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.23.0
    hooks:
      - id: commitlint
        name: Lint commit message
        additional_dependencies: ['@commitlint/config-conventional']
        stages: [commit-msg]
