"$schema" = 'https://starship.rs/config-schema.json'

format = """
$hostname\
$username\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$fill\
$c\
$cmake\
$golang\
$java\
$lua\
$nodejs\
$perl\
$python\
$ruby\
$rust\
$swift\
$zig\
$package\
$line_break\
$character
"""

palette = "nord"

[palettes.nord]
nord00 = "#2E3440"
nord01 = "#3B4252"
nord02 = "#434C5E"
nord03 = "#4C566A"
nord04 = "#D8DEE9"
nord05 = "#E5E9F0"
nord06 = "#ECEFF4"
nord07 = "#8FBCBB"
nord08 = "#88C0D0"
nord09 = "#81A1C1"
nord10 = "#5E81AC"
nord11 = "#BF616A"
nord12 = "#D08770"
nord13 = "#e7c175"
nord14 = "#A3BE8C"
nord15 = "#B48EAD"

[hostname]
ssh_symbol = ""
style = "bold nord14"
format = "[$ssh_symbol $hostname ]($style)"

[username]
style_root = "bold nord11"
style_user = "bold nord13"
format = "[$user ]($style)"
show_always = false

[username.aliases]
yvanyo = "YvanYo"
yihyu = "Yihuang"

[directory]
style = "nord09"
read_only = "⊗"
read_only_style = "nord11"

[git_branch]
symbol = ""
format = "[$branch]($style)"
style = "nord03"

[git_state]
style = "dimmed nord13"
format = '[\($state( $progress_current/$progress_total)\) ]($style)'

[git_status]
style = "nord08"
format = "[[(*$untracked) ](nord02)($ahead_behind) ]($style)"
ahead = "↑"
behind = "↓"
untracked = "?"

[cmd_duration]
style = "bold nord13"
format = "[$duration]($style)"

[fill]
symbol = " "

[c]
symbol = ""
style = "nord07"
format = "[ $symbol]($style)"

[cmake]
symbol = ""
style = "nord07"
format = "[ $symbol]($style)"

[golang]
symbol = ""
style = "nord07"
format = "[ $symbol]($style)"

[java]
symbol = "󰬷"
style = "nord07"
format = "[ $symbol]($style)"

[lua]
symbol = "󰢱"
style = "nord07"
format = "[ $symbol]($style)"

[nodejs]
symbol = "󰎙"
style = "nord07"
format = "[ $symbol]($style)"

[perl]
symbol = ""
style = "nord07"
format = "[ $symbol]($style)"

[python]
symbol = "󰌠"
style = "nord07"
format = "[ $symbol]($style)"

[ruby]
symbol = "󰴭"
style = "nord07"
format = "[ $symbol]($style)"

[rust]
symbol = "󱘗"
style = "nord07"
format = "[ $symbol]($style)"

[swift]
symbol = "󰛥"
style = "nord07"
format = "[ $symbol]($style)"

[zig]
symbol = ""
style = "nord07"
format = "[ $symbol]($style)"

[package]
symbol = ""
style = "nord07"
format = "[ $symbol]($style)"

[character]
success_symbol = "[❯](nord15)"
error_symbol = "[❯](nord11)"
vimcmd_symbol = "[❮](nord14)"
