auto_sync = false
update_check = false
filter_mode_shell_up_key_binding = "session"
search_mode_shell_up_key_binding = "prefix"
style = "compact"
inline_height = 18
enter_accept = true

[sync]
records = true

[logs]
enabled = false
