theme = "nord"

[editor]
auto-completion = true
auto-format = true
auto-pairs = true
auto-save = true
bufferline = "multiple"
color-modes = true
cursorline = true
editor-config = true
end-of-line-diagnostics = "hint"
line-number = "relative"
preview-completion-insert = true
text-width = 80
trim-trailing-whitespace = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 0

[editor.lsp]
enable = true
display-progress-messages = true
auto-signature-help = true
display-inlay-hints = true
snippets = true

[editor.search]
smart-case = true
wrap-around = true

[editor.smart-tab]
enable = true
supersede-menu = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding", "file-type", "total-line-numbers"]
separator = "│"
mode.normal = "Normal"
mode.insert = "Insert"
mode.select = "Select"

[editor.whitespace.render]
nbsp = "all"
newline = "none"
space = "none"
tab = "all"
