name: Auto-merge bot PRs

on:
  pull_request_target:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  autoMerge:
    name: Auto-merge bot PRs
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.user.type == 'Bot' &&
      (github.event.pull_request.user.login == 'pre-commit-ci[bot]' ||
        github.event.pull_request.user.login == 'dependabot[bot]')

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_LABELS: ""
